all		:
	g++ -g -Wall -Werror -Wextra -std=c++17 main_test_stack.cpp s21_stack.h_ s21_stack.tpp s21_utils.h_
#	g++ -g -Wall -Werror -Wextra -std=c++17 main_test_queue.cpp s21_queue.h_ s21_queue.tpp s21_utils.h_